name: Build and push multi-arch

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          tags: ghcr.io/devinrsmith/multi-arch-image-description:latest
          push: true
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=My multi-arch image
